# Generated by Django 4.0.2 on 2022-02-10 16:09

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('disc_start', models.DateField(auto_now_add=True, verbose_name='Discount start at')),
                ('disc_end', models.DateField(auto_now_add=True, verbose_name='Discount end at')),
                ('cars', models.ManyToManyField(to='car.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Showroom name')),
                ('features', models.JSONField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Balance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowroomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='showroom',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, through='showroom.ShowroomCar', to='car.Car'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='current_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='showroom.discountshowroom'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.location'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='sale_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='showroom.showroomhistory'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='unique_customers',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='discountshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom'),
        ),
    ]
