# Generated by Django 4.0.2 on 2022-02-09 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('disc_start', models.DateField(default=datetime.datetime(2022, 2, 9, 15, 11, 28, 973695, tzinfo=utc), verbose_name='Discount start at')),
                ('disc_end', models.DateField(default=datetime.datetime(2022, 2, 9, 15, 11, 28, 973714, tzinfo=utc), verbose_name='Discount end at')),
                ('is_active', models.BooleanField(default=True)),
                ('cars', models.ManyToManyField(to='car.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Showroom name')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('features', models.JSONField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 11, 28, 900389))),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('showroom_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowroomCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('qty', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='showroom',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, through='showroom.ShowroomCar', to='car.Car'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='current_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.discountshowroom'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='sale_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.showroomhistory'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='unique_customers',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Customer'),
        ),
    ]
