# Generated by Django 4.0.2 on 2022-02-09 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('disc_start', models.DateField(default=datetime.datetime(2022, 2, 9, 15, 11, 28, 977094, tzinfo=utc), verbose_name='Discount start at')),
                ('disc_end', models.DateField(default=datetime.datetime(2022, 2, 9, 15, 11, 28, 977108, tzinfo=utc), verbose_name='Discount end at')),
                ('cars', models.ManyToManyField(to='car.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 11, 28, 900389))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 11, 28, 900512))),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Supplier name')),
                ('foundation', models.DateField(blank=True, default=2022, verbose_name='Foundation date')),
                ('cars', models.ManyToManyField(to='car.Car')),
                ('current_discount', models.ManyToManyField(blank=True, null=True, to='supplier.DiscountSupplier')),
                ('deal_history', models.ManyToManyField(blank=True, null=True, to='supplier.SupplierHistory')),
                ('showrooms', models.ManyToManyField(blank=True, null=True, to='showroom.Showroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
