# Generated by Django 4.0.2 on 2022-02-09 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_discountsupplier_disc_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountsupplier',
            name='disc_end',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 15, 17, 16, 362840, tzinfo=utc), verbose_name='Discount end at'),
        ),
        migrations.AlterField(
            model_name='discountsupplier',
            name='disc_start',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 15, 17, 16, 362828, tzinfo=utc), verbose_name='Discount start at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 17, 16, 274261)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 17, 16, 274389)),
        ),
    ]
