# Generated by Django 4.0.2 on 2022-02-09 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 11, 28, 900389))),
                ('manufacturer_name', models.CharField(max_length=100, unique=True, verbose_name='Manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 11, 28, 900389))),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Car model')),
                ('features', models.JSONField()),
                ('description', models.TextField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmanufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
