# Generated by Django 4.0.2 on 2022-02-09 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 14, 14, 777465)),
        ),
        migrations.AlterField(
            model_name='carmanufacturer',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 14, 14, 777465)),
        ),
    ]
