# Generated by Django 4.0.2 on 2022-02-09 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhistory',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 9, 15, 15, 26, 20092)),
        ),
    ]
